server:
  port: 8083
  servlet:
    context-path: /ui2

security:
  oauth2:
    client:
      clientId: SampleClientId2
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
      jwt:
        key-uri: http://localhost:8081/auth/oauth/token_key

spring:
  #redis
  redis:
    host: 192.168.188.130
    port: 6379

  #Session
  session:
    store-type: redis

logging:
  level:
    com:
      github:
        yahyaoo: debug
    org:
      springframework:
        security: debug
